### ISSUE TITLE
Query to create payment_transaction table

### ISSUE THREAD

**Issue by Sem4enko** [Sem4enko/asd-java-intern#40]
CREATE TABLE payment_transaction(
  id INT NOT NULL AUTO_INCREMENT,
  payment_provider INT NOT NULL,
  created_date DATETIME NOT NULL,
  reservation_id INT NOT NULL,
  funds_holder TINYINT(4) NOT NULL,
  partial_iin VARCHAR(4) NULL,
  status VARCHAR(15) NOT NULL,
  message VARCHAR(1000) NULL,
  partner_id INT NULL,
  supplier_id INT NULL,
  currency VARCHAR(3) NOT NULL,
  total_commission DOUBLE NOT NULL,
  partner_payment DOUBLE NULL,
  bp_payment DOUBLE NULL,
  credit_card_fee DOUBLE NULL,
  final_amount DOUBLE NULL,
  charge_type VARCHAR(15) NULL,
  version TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);

**Comment by rdovgan** [comment]
@Sem4enko done
