### ISSUE TITLE
CREATE TABLE pending_transaction

### ISSUE THREAD

**Issue by Sem4enko** [Sem4enko/asd-java-intern#50]
CREATE TABLE pending_transaction(
  id INT NOT NULL AUTO_INCREMENT,
  reservation_id INT NOT NULL,
   partial_iin VARCHAR(4) DEFAULT NULL,
  charge_date DATETIME NOT NULL,
  charge_amount DOUBLE NOT NULL,
  status VARCHAR(15) NOT NULL,
  version TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

**Comment by rdovgan** [comment]
@Sem4enko done
