### ISSUE TITLE
CREATE TABLE payment_gateway_provider

### ISSUE THREAD

**Issue by Sem4enko** [Sem4enko/asd-java-intern#52]
CREATE TABLE payment_gateway_provider(
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(25) NOT NULL,
fee DOUBLE NOT NULL,
autopay tinyint NOT NULL,
support_split_payment tinyint NOT NULL,
version TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (id)
);

**Comment by rdovgan** [comment]
@Sem4enko done
